export enum Heroes {
  'Anti-Mage' = 1,
  'Axe',
  'Bane',
  'Bloodseeker',
  'Crystal Maiden',
  'Drow Ranger',
  'Earthshaker',
  'Juggernaut',
  'Mirana',
  'Morphling', // id: 10
  'Shadow Fiend',
  'Phantom Lancer',
  'Puck',
  'Pudge',
  'Razor',
  'Sand King',
  'Storm Spirit',
  'Sven',
  'Tiny',
  'Vengeful Spirit', // id: 20
  'Windranger',
  'Zeus',
  'Kunkka',
  'Lina' = 25,
  'Lion',
  'Shadow Shaman',
  'Slardar',
  'Tidehunter',
  'Witch Doctor', // id: 30 (Skip at Kunka/Lina by 1)
  'Lich',
  'Riki',
  'Enigma',
  'Tinker',
  'Sniper',
  'Necrophos',
  'Warlock',
  'Beastmaster',
  'Queen of Pain',
  'Venomancer', // id: 40
  'Faceless Void',
  'Wraith King',
  'Death Prophet',
  'Phantom Assassin',
  'Pugna',
  'Templar Assassin',
  'Viper',
  'Luna',
  'Dragon Knight',
  'Dazzle', // id: 50
  'Clockwerk',
  'Leshrac',
  "Nature's Prophet",
  'Lifestealer',
  'Dark Seer',
  'Clinkz',
  'Omniknight',
  'Enchantress',
  'Huskar',
  'Night Stalker', // id: 60
  'Broodmother',
  'Bounty Hunter',
  'Weaver',
  'Jakiro',
  'Batrider',
  'Chen',
  'Spectre',
  'Ancient Apparition',
  'Doom',
  'Ursa', // id: 70
  'Spirit Breaker',
  'Gyrocopter',
  'Alchemist',
  'Invoker',
  'Silencer',
  'Outworld Devourer',
  'Lycan',
  'Brewmaster',
  'Shadow Demon',
  'Lone Druid', // id: 80
  'Chaos Knight',
  'Meepo',
  'Treant Protector',
  'Ogre Magi',
  'Undying',
  'Rubick',
  'Disruptor',
  'Nyx Assassin',
  'Naga Siren',
  'Keeper of the Light', // id: 90
  'Wisp',
  'Visage',
  'Slark',
  'Medusa',
  'Troll Warlord',
  'Centaur Warrunner',
  'Magnus',
  'Timbersaw',
  'Bristleback',
  'Tusk', // id: 100
  'Skywrath Mage',
  'Abaddon',
  'Elder Titan',
  'Legion Commander',
  'Techies',
  'Ember Spirit',
  'Earth Spirit',
  'Underlord',
  'Terrorblade',
  'Phoenix', //id: 110
  'Oracle',
  'Winter Wyvern',
  'Arc Warden',
  'Monkey King',
  'Dark Willow' = 119,
  'Pangolier', // id: 120 (skip at Monkey King/Dark Willow by 6)
  'Grimstroke',
  'Hoodwink' = 123,
  'Void Spirit' = 126,
  'Snapfire' = 128,
  'Mars',
  'Dawnbreaker' = 135, // multiple skips between 120 and 135
}

export enum ItemsEnum {
  'Blades of Attack' = 2,
  'Chainmail' = 4,
  'Quelling Blade' = 11,
  'Ring of Protection' = 12,
  'Gauntlets of Strength' = 13,
  'Slippers of Agility' = 14,
  'Mantle of Intelligence' = 15,
  'Iron Branch' = 16,
  'Belt of Strength' = 17,
  'Band of Elvenskin' = 18,
  'Robe of the Magi' = 19,
  'Circlet' = 20,
  'Gloves of Haste' = 25,
  'Ring of Regen' = 27,
  "Sage's Mask" = 28,
  'Boots of Speed' = 29,
  'Cloak' = 31,
  'Magic Stick' = 34,
  'Magic Wand' = 36,
  'Clarity' = 38,
  'Healing Salve' = 39,
  'Dust of Appearance' = 40,
  'Observer Ward' = 42,
  'Sentry Ward' = 43,
  'Tango' = 44,
  'Bracer' = 73,
  'Wraith Band' = 75,
  'Null Talisman' = 77,
  'Buckler' = 86,
  'Ring of Basilius' = 88,
  'Headdress' = 94,
  'Orb of Venom' = 181,
  'Smoke of Deceit' = 188,
  'Enchanted Mango' = 216,
  'Faerie Fire' = 237,
  'Blight Stone' = 240,
  'Wind Lace' = 244,
  'Crown' = 261,
  'Raindrops' = 265,
  'Fluffy Hat' = 593,
}
